export interface employeeModel{
    empId: number;
    departmentId: number;
    departmentName: string;
    fullName: string;
    gender: string;
    profileImage: string;
    empCode: string;
    roleId: number;
    roleName: string;
    emailId: number;
    reportingManager: string;
    teamId: number;
    teamName: string;
    empType: string;
    actualEmployementDate: number;
    pastExperience: number;
    dateOfJoining: number;
    permanentAddress: string;
    presentAddress: string;
    phoneNumber: number;
    emergencyNumber: number;
    panNo: string;
    aadharNo: number;
    dateOfBirth: number;
    createdDate: number;
    modifiedDate: number;
    isActive: boolean;
}